package condensetechcdkconstructs


// Properties for the MonitoringFacade.
// Experimental.
type MonitoringFacadeProps struct {
	// The ARN of the SNS topic to use for alarms.
	// Experimental.
	TopicArn *string `field:"required" json:"topicArn" yaml:"topicArn"`
	// The name of the Cloudwatch dashboard to create.
	// Default: - A name is generated by CDK.
	//
	// Experimental.
	DashboardName *string `field:"optional" json:"dashboardName" yaml:"dashboardName"`
}

