package condensetechcdkconstructs

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/condensetech/cdk-constructs/condensetechcdkconstructs/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awscloudfront"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/condensetech/cdk-constructs/condensetechcdkconstructs/internal"
)

// A CloudFront function that implements a naive basic auth mechanism.
//
// The function is naive because the basic auth string isn't treated as a secret and it's hardcoded in the function code.
//
// This function is useful for simple use cases where you need to protect a CloudFront distribution with basic auth. A typical use case is to ensure that a staging environment isn't indexed by crawlers (just in case robots.txt is totally ignored).
// Experimental.
type NaiveBasicAuthCloudfrontFunction interface {
	awscloudfront.Function
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	// Experimental.
	Env() *awscdk.ResourceEnvironment
	// the ARN of the CloudFront function.
	// Experimental.
	FunctionArn() *string
	// the name of the CloudFront function.
	// Experimental.
	FunctionName() *string
	// the runtime of the CloudFront function.
	// Experimental.
	FunctionRuntime() *string
	// the deployment stage of the CloudFront function.
	// Experimental.
	FunctionStage() *string
	// The tree node.
	// Experimental.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	// The stack in which this resource is defined.
	// Experimental.
	Stack() awscdk.Stack
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	// Experimental.
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	// Experimental.
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	// Experimental.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	// Experimental.
	GetResourceNameAttribute(nameAttr *string) *string
	// Returns a string representation of this construct.
	// Experimental.
	ToString() *string
}

// The jsii proxy struct for NaiveBasicAuthCloudfrontFunction
type jsiiProxy_NaiveBasicAuthCloudfrontFunction struct {
	internal.Type__awscloudfrontFunction
}

func (j *jsiiProxy_NaiveBasicAuthCloudfrontFunction) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_NaiveBasicAuthCloudfrontFunction) FunctionArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"functionArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_NaiveBasicAuthCloudfrontFunction) FunctionName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"functionName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_NaiveBasicAuthCloudfrontFunction) FunctionRuntime() *string {
	var returns *string
	_jsii_.Get(
		j,
		"functionRuntime",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_NaiveBasicAuthCloudfrontFunction) FunctionStage() *string {
	var returns *string
	_jsii_.Get(
		j,
		"functionStage",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_NaiveBasicAuthCloudfrontFunction) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_NaiveBasicAuthCloudfrontFunction) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_NaiveBasicAuthCloudfrontFunction) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Experimental.
func NewNaiveBasicAuthCloudfrontFunction(scope constructs.Construct, id *string, props *NaiveBasicAuthCloudfrontFunctionProps) NaiveBasicAuthCloudfrontFunction {
	_init_.Initialize()

	if err := validateNewNaiveBasicAuthCloudfrontFunctionParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_NaiveBasicAuthCloudfrontFunction{}

	_jsii_.Create(
		"@condensetech/cdk-constructs.NaiveBasicAuthCloudfrontFunction",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Experimental.
func NewNaiveBasicAuthCloudfrontFunction_Override(n NaiveBasicAuthCloudfrontFunction, scope constructs.Construct, id *string, props *NaiveBasicAuthCloudfrontFunctionProps) {
	_init_.Initialize()

	_jsii_.Create(
		"@condensetech/cdk-constructs.NaiveBasicAuthCloudfrontFunction",
		[]interface{}{scope, id, props},
		n,
	)
}

// Imports a function by its name and ARN.
// Experimental.
func NaiveBasicAuthCloudfrontFunction_FromFunctionAttributes(scope constructs.Construct, id *string, attrs *awscloudfront.FunctionAttributes) awscloudfront.IFunction {
	_init_.Initialize()

	if err := validateNaiveBasicAuthCloudfrontFunction_FromFunctionAttributesParameters(scope, id, attrs); err != nil {
		panic(err)
	}
	var returns awscloudfront.IFunction

	_jsii_.StaticInvoke(
		"@condensetech/cdk-constructs.NaiveBasicAuthCloudfrontFunction",
		"fromFunctionAttributes",
		[]interface{}{scope, id, attrs},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Deprecated: use `x instanceof Construct` instead.
func NaiveBasicAuthCloudfrontFunction_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateNaiveBasicAuthCloudfrontFunction_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@condensetech/cdk-constructs.NaiveBasicAuthCloudfrontFunction",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
// Experimental.
func NaiveBasicAuthCloudfrontFunction_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateNaiveBasicAuthCloudfrontFunction_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@condensetech/cdk-constructs.NaiveBasicAuthCloudfrontFunction",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
// Experimental.
func NaiveBasicAuthCloudfrontFunction_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateNaiveBasicAuthCloudfrontFunction_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@condensetech/cdk-constructs.NaiveBasicAuthCloudfrontFunction",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (n *jsiiProxy_NaiveBasicAuthCloudfrontFunction) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := n.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		n,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (n *jsiiProxy_NaiveBasicAuthCloudfrontFunction) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		n,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (n *jsiiProxy_NaiveBasicAuthCloudfrontFunction) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := n.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		n,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (n *jsiiProxy_NaiveBasicAuthCloudfrontFunction) GetResourceNameAttribute(nameAttr *string) *string {
	if err := n.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		n,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (n *jsiiProxy_NaiveBasicAuthCloudfrontFunction) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		n,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

